-- DROP TABLE t143076_users

CREATE TABLE t143076_users (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    createdAt DATETIME NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    displayName VARCHAR(255) NOT NULL,
    fullName VARCHAR(255) NOT NULL
)

-- DROP TABLE t143076_pictures
