DROP TABLE t143076_users;

CREATE TABLE t143076_users (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    createdAt DATETIME NOT NULL DEFAULT now(),
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    displayName VARCHAR(255),
    fullName VARCHAR(255)
);

-- DROP TABLE t143076_pictures;
